# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- hosts: primary
  roles:
    - ensure-python
    - ensure-pip
    - ensure-tox
    - start-zuul-console
    - clear-firewall
    - ensure-docker
  tasks:
    - name: Install deps for tests
      shell: |
        set -x
        ./tools/deployment/000-install-packages.sh
        ./tools/deployment/002-build-charts.sh
        sudo fdisk --list
        df -h
        sudo mkdir -p /opt/ext_vol
        BIG_VOLUME=$(sudo fdisk -l 2>&1 | grep  -E 80G | grep Linux | awk '{print $1}')
        if ! mount | grep "${BIG_VOLUME}"
        then
            sudo mkfs.ext4 "${BIG_VOLUME}"
            sudo mount "${BIG_VOLUME}" /opt/ext_vol
            df -h
        fi
        ./tools/deployment/003-deploy-k8s.sh
        ./tools/deployment/004-make-images.sh
      args:
        chdir: "{{ zuul.project.src_dir }}/{{ args.chdir }}"
        executable: /bin/bash
      environment:
        DISTRO: "{{ distro_suffix | default('') }}"
      become: True
    - name: Run gate scripts
      include_role:
        name: osh-run-script
      vars:
        gate_script_path: "{{ item }}"
      with_items: "{{ gate_scripts }}"
