[tox]
minversion = 3.4
envlist = dev,pep8,py36,bandit,docs,list-tests
skipsdist = true

[testenv:dev]
useddevelop = True
basepython = python3
passenv = http_proxy HTTP_PROXY https_proxy HTTPS_PROXY no_proxy NO_PROXY
setenv =
  VIRTUAL_ENV={envdir}
  PYTHONWARNINGS=default::DeprecationWarning

deps =
  freeze-req: -r{toxinidir}/requirements-frozen.txt
  list-tests: -r {toxinidir}/requirements-frozen.txt

envdir=
  {toxinidir}/.tox/{envname}

commands_pre =
  find . -type f -name "*.pyc"
  list-tests: stestr init

[testenv:venv]
commands = {posargs}

[testenv:py36]
setenv =
  PYTHONWARNING=all
deps = -r{toxinidir}/requirements-frozen.txt
       -r{toxinidir}/test-requirements.txt
commands =
    pytest  {posargs}

[testenv:bandit]
deps =
    -r{toxinidir}/test-requirements.txt
commands =
    bandit -r {toxinidir}

[testenv:docs]
whitelist_externals = rm
deps =
    -r{toxinidir}/docs/requirements.txt
commands =
    rm -rf docs/build
    sphinx-build -W -b html docs/source docs/build/html

[testenv:pep8]
deps =
    -r{toxinidir}/test-requirements.txt
commands =
    yapf -rd {toxinidir} {toxinidir}/tests
    flake8 {toxinidir}
    bandit -r {toxinidir}
