ARG FROM=docker.io/ubuntu:bionic
FROM ${FROM}

LABEL org.opencontainers.image.authors='airship-discuss@lists.airshipit.org, irc://#airshipit@freenode' \
      org.opencontainers.image.url='https://airshipit.org' \
      org.opencontainers.image.documentation='https://opendev.org/airship/porthole' \
      org.opencontainers.image.source='https://opendev.org/airship/porthole' \
      org.opencontainers.image.vendor='The Airship Authors' \
      org.opencontainers.image.licenses='Apache-2.0'

ARG DEBIAN_FRONTEND=noninteractive

RUN set -xe && \
    sed -i '/nobody/d' /etc/passwd && \
    echo "nobody:x:65534:65534:nobody:/nonexistent:/bin/bash" >> /etc/passwd && \
    apt-get update && \
    apt-get install -y \
      bash \
      sudo \
      rsyslog \
      python3 \
      python3-pip &&\
    pip3 install \
      oslo.rootwrap==5.8.0 \
      python-openstackclient==3.18.1 \
      python-glanceclient==2.16.0 \
      python-novaclient==13.0.2 \
      python-neutronclient==6.12.0 \
      python-cinderclient==4.2.1 && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
