ARG FROM=docker.io/ubuntu:jammy
FROM ${FROM}

LABEL org.opencontainers.image.authors='airship-discuss@lists.airshipit.org, irc://#airshipit@freenode' \
      org.opencontainers.image.url='https://airshipit.org' \
      org.opencontainers.image.documentation='https://opendev.org/airship/porthole' \
      org.opencontainers.image.source='https://opendev.org/airship/porthole' \
      org.opencontainers.image.vendor='The Airship Authors' \
      org.opencontainers.image.licenses='Apache-2.0'

ARG DEBIAN_FRONTEND=noninteractive

RUN set -xe \
    && sed -i '/nobody/d' /etc/passwd \
    && echo "nobody:x:65534:65534:nobody:/nonexistent:/bin/bash" >> /etc/passwd \
    && apt-get update && apt-get upgrade -y \
    && apt-get install --no-install-recommends -y \
         bash \
         sudo \
         rsyslog \
         python3.10 \
         python3-pip \
         python3-netifaces \
         orphan-sysvinit-scripts \
    && pip3 install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir \
         munch \
         oslo.rootwrap==7.0.1 \
         python-openstackclient==6.2.0 \
         python-glanceclient==4.3.0 \
         python-novaclient==18.3.0 \
         python-neutronclient==9.0.0 \
         python-cinderclient==9.3.0 \
         python-heatclient==3.2.0 \
         osc-placement \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

RUN PYTHON_LOCATION=$(pip3 show oslo.rootwrap|grep Location|awk '{print $2}') \
    && sed -i "/rootwrap_logger.setLevel/s/.*/#&/" $PYTHON_LOCATION/oslo_rootwrap/wrapper.py \
    && sed -i "/handler.setFormatter/s/.*/#&/" $PYTHON_LOCATION/oslo_rootwrap/wrapper.py \
    && sed -i "/os.path.basename/s/.*/#&/" $PYTHON_LOCATION/oslo_rootwrap/wrapper.py \
    && sed -i "/rootwrap_logger.addHandler/s/.*/#&/" $PYTHON_LOCATION/oslo_rootwrap/wrapper.py

CMD ["/bin/bash"]
