ARG FROM=docker.io/ubuntu:bionic
FROM ${FROM}

LABEL org.opencontainers.image.authors='airship-discuss@lists.airshipit.org, irc://#airshipit@freenode' \
      org.opencontainers.image.url='https://airshipit.org' \
      org.opencontainers.image.documentation='https://opendev.org/airship/porthole' \
      org.opencontainers.image.source='https://opendev.org/airship/porthole' \
      org.opencontainers.image.vendor='The Airship Authors' \
      org.opencontainers.image.licenses='Apache-2.0'

ARG DEBIAN_FRONTEND=noninteractive

RUN set -xe \
    && sed -i '/nobody/d' /etc/passwd \
    && echo "nobody:x:65534:65534:nobody:/nonexistent:/bin/bash" >> /etc/passwd \
    && apt-get update \
    && apt-get install -y \
       bash \
       sudo \
       rsyslog \
       python3.6 \
       python3-pip \
    && pip3 install --upgrade pip \
    && pip3 install \
         oslo.rootwrap==6.0.2 \
         python-openstackclient==5.2.0 \
         python-glanceclient==3.1.2 \
         python-novaclient==17.0.0 \
         python-neutronclient==7.1.1 \
         python-cinderclient==7.0.1 \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i "/rootwrap_logger.setLevel/s/.*/#&/" /usr/local/lib/python3.6/dist-packages/oslo_rootwrap/wrapper.py \
    && sed -i "/handler.setFormatter/s/.*/#&/" /usr/local/lib/python3.6/dist-packages/oslo_rootwrap/wrapper.py \
    && sed -i "/os.path.basename/s/.*/#&/" /usr/local/lib/python3.6/dist-packages/oslo_rootwrap/wrapper.py \
    && sed -i "/rootwrap_logger.addHandler/s/.*/#&/" /usr/local/lib/python3.6/dist-packages/oslo_rootwrap/wrapper.py

CMD ["/bin/bash"]
