ARG FROM=docker.io/ubuntu:bionic
FROM ${FROM}

LABEL org.opencontainers.image.authors='airship-discuss@lists.airshipit.org, irc://#airshipit@freenode' \
      org.opencontainers.image.url='https://airshipit.org' \
      org.opencontainers.image.documentation='https://opendev.org/airship/porthole' \
      org.opencontainers.image.source='https://opendev.org/airship/porthole' \
      org.opencontainers.image.vendor='The Airship Authors' \
      org.opencontainers.image.licenses='Apache-2.0'

ARG DEBIAN_FRONTEND=noninteractive

RUN set -xe && \
    sed -i '/nobody/d' /etc/passwd && \
    echo "nobody:x:65534:65534:nobody:/nonexistent:/bin/bash" >> /etc/passwd && \
    apt-get update && \
    apt-get install -y \
      bash \
      rsyslog \
      python3 \
      python3-pip \
      python3-oslo.rootwrap \
      python3-openstackclient \
      python3-glanceclient \
      python3-novaclient \
      python3-neutronclient \
      python3-cinderclient && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
