ARG FROM=docker.io/ubuntu:xenial
FROM ${FROM}

LABEL org.opencontainers.image.authors='airship-discuss@lists.airshipit.org, irc://#airshipit@freenode' \
      org.opencontainers.image.url='https://airshipit.org' \
      org.opencontainers.image.documentation='https://opendev.org/airship/porthole' \
      org.opencontainers.image.source='https://opendev.org/airship/porthole' \
      org.opencontainers.image.vendor='The Airship Authors' \
      org.opencontainers.image.licenses='Apache-2.0'

RUN set -xe \
    && echo '#!/bin/sh' > /usr/sbin/policy-rc.d \
    && echo 'exit 101' >> /usr/sbin/policy-rc.d \
    && chmod +x /usr/sbin/policy-rc.d \
    && sed -i '/nobody/d' /etc/passwd \
    && echo "nobody:x:65534:65534:nobody:/nonexistent:/bin/bash" >> /etc/passwd \
    && dpkg-divert --local --rename --add /sbin/initctl \
    && cp -a /usr/sbin/policy-rc.d /sbin/initctl \
    && sed -i 's/^exit.*/exit 0/' /sbin/initctl \
    && apt-get update \
    && apt-get install -y \
         bash\
         moreutils \
         sudo \
         rsyslog \
         x11-apps \
         python-oslo.rootwrap \
         python-openstackclient \
         python3-oslo.rootwrap \
         python3-openstackclient \
         python3-glanceclient \
         python3-novaclient \
         python3-neutronclient \
         python3-cinderclient \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
