ARG FROM=docker.io/ubuntu:focal
FROM ${FROM}

LABEL org.opencontainers.image.authors='airship-discuss@lists.airshipit.org, irc://#airshipit@freenode' \
      org.opencontainers.image.url='https://airshipit.org' \
      org.opencontainers.image.documentation='https://opendev.org/airship/porthole' \
      org.opencontainers.image.source='https://opendev.org/airship/porthole' \
      org.opencontainers.image.vendor='The Airship Authors' \
      org.opencontainers.image.licenses='Apache-2.0'

ARG DEBIAN_FRONTEND=noninteractive

RUN set -xe \
    && sed -i '/nobody/d' /etc/passwd \
    && echo "nobody:x:65534:65534:nobody:/nonexistent:/bin/bash" >> /etc/passwd \
    && apt-get update && apt-get upgrade -y \
    && apt-get install -y \
       bash \
       sudo \
       rsyslog \
       python3.8 \
       python3-pip \
    && pip3 install --upgrade pip \
    && pip3 install \
        oslo.rootwrap==6.2.0 \
        python-openstackclient==5.4.0 \
        python-glanceclient==3.2.2 \
        python-novaclient==17.2.1 \
        python-neutronclient==7.2.1 \
        python-cinderclient==7.2.2 \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

RUN PYTHON_LOCATION=$(pip3 show oslo.rootwrap|grep Location|awk '{print $2}') \
    && sed -i "/rootwrap_logger.setLevel/s/.*/#&/" $PYTHON_LOCATION/oslo_rootwrap/wrapper.py \
    && sed -i "/handler.setFormatter/s/.*/#&/" $PYTHON_LOCATION/oslo_rootwrap/wrapper.py \
    && sed -i "/os.path.basename/s/.*/#&/" $PYTHON_LOCATION/oslo_rootwrap/wrapper.py \
    && sed -i "/rootwrap_logger.addHandler/s/.*/#&/" $PYTHON_LOCATION/oslo_rootwrap/wrapper.py

CMD ["/bin/bash"]
