---
# Copyright 2019 AT&T Intellectual Property.  All other rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    check:
      jobs:
        - airship-porthole-linter
        - openstack-tox-pep8
        - openstack-tox-docs
        - airship-porthole-openstack-tox-py310-kubeadm
        - airship-porthole-openstack-tox-cover-kubeadm
        # Ubuntu Jammy
        - airship-porthole-images-jammy-build-calicoctl-utility
        - airship-porthole-images-jammy-build-ceph-utility
        - airship-porthole-images-jammy-build-compute-utility
        - airship-porthole-images-jammy-build-kubeadm-utility
        - airship-porthole-images-jammy-build-etcdctl-utility
        - airship-porthole-images-jammy-build-mysqlclient-utility
        - airship-porthole-images-jammy-build-openstack-utility
        - airship-porthole-images-jammy-build-postgresql-utility
        - airship-porthole-run-functional-tests-ubuntu_jammy-kubeadm-2025-2
        - airship-porthole-run-functional-tests-ubuntu_jammy-kubeadm-2025-1
        # Ubuntu Noble
        - airship-porthole-images-noble-build-calicoctl-utility
        - airship-porthole-images-noble-build-ceph-utility
        - airship-porthole-images-noble-build-compute-utility
        - airship-porthole-images-noble-build-kubeadm-utility
        - airship-porthole-images-noble-build-etcdctl-utility
        - airship-porthole-images-noble-build-mysqlclient-utility
        - airship-porthole-images-noble-build-openstack-utility
        - airship-porthole-images-noble-build-postgresql-utility
        - airship-porthole-run-functional-tests-ubuntu_noble-kubeadm-2025-2

    gate:
      jobs:
        - airship-porthole-linter
        - openstack-tox-pep8
        - openstack-tox-docs
        - airship-porthole-openstack-tox-py310-kubeadm
        - airship-porthole-openstack-tox-cover-kubeadm
        # Ubuntu Jammy
        - airship-porthole-images-jammy-build-calicoctl-utility
        - airship-porthole-images-jammy-build-ceph-utility
        - airship-porthole-images-jammy-build-compute-utility
        - airship-porthole-images-jammy-build-kubeadm-utility
        - airship-porthole-images-jammy-build-etcdctl-utility
        - airship-porthole-images-jammy-build-mysqlclient-utility
        - airship-porthole-images-jammy-build-openstack-utility
        - airship-porthole-images-jammy-build-postgresql-utility
        # Ubuntu Noble
        - airship-porthole-images-noble-build-calicoctl-utility
        - airship-porthole-images-noble-build-ceph-utility
        - airship-porthole-images-noble-build-compute-utility
        - airship-porthole-images-noble-build-kubeadm-utility
        - airship-porthole-images-noble-build-etcdctl-utility
        - airship-porthole-images-noble-build-mysqlclient-utility
        - airship-porthole-images-noble-build-openstack-utility
        - airship-porthole-images-noble-build-postgresql-utility

    post:
      jobs:
        - porthole-upload-git-mirror
        # Ubuntu Jammy
        - airship-porthole-images-jammy-publish-calicoctl-utility
        - airship-porthole-images-jammy-publish-ceph-utility
        - airship-porthole-images-jammy-publish-compute-utility
        - airship-porthole-images-jammy-publish-kubeadm-utility
        - airship-porthole-images-jammy-publish-etcdctl-utility
        - airship-porthole-images-jammy-publish-mysqlclient-utility
        - airship-porthole-images-jammy-publish-openstack-utility
        - airship-porthole-images-jammy-publish-postgresql-utility
        # Ubuntu Noble
        - airship-porthole-images-noble-publish-calicoctl-utility
        - airship-porthole-images-noble-publish-ceph-utility
        - airship-porthole-images-noble-publish-compute-utility
        - airship-porthole-images-noble-publish-kubeadm-utility
        - airship-porthole-images-noble-publish-etcdctl-utility
        - airship-porthole-images-noble-publish-mysqlclient-utility
        - airship-porthole-images-noble-publish-openstack-utility
        - airship-porthole-images-noble-publish-postgresql-utility


- job:
    name: airship-porthole-images
    abstract: true
    timeout: 7200
    post-timeout: 7200
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: treasuremap-airskiff-1node-ubuntu_jammy
    vars:
      publish: false
      tags:
        dynamic:
          branch: true
          commit: false
        static:
          - latest
      args:
        chdir: ../porthole

- job:
    name: airship-porthole-linter
    description: |
      Lints files for trailing whitespace
    run: tools/gate/playbooks/zuul-linter.yaml
    timeout: 300
    nodeset: treasuremap-airskiff-1node-ubuntu_jammy
    vars:
      args:
        chdir: ../porthole

- job:
    name: porthole-infra-deploy
    parent: treasuremap-airskiff-infra-deploy-base
    abstract: true
    required-projects:
      - name: airship/treasuremap
        override-checkout: v1.9
    roles:
      - zuul: airship/treasuremap
    irrelevant-files: &irrelevant-files
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
    vars:
      treasuremap_ref: v1.9
      args:
        chdir: ../../airship/porthole
      zuul_osh_relative_path: ../../openstack/openstack-helm
      zuul_treasuremap_relative_path: ../../airship/treasuremap
      gate_scripts_relative_path: ../../airship/porthole
      distro_suffix: ubuntu_jammy
      gate_scripts:
        - ./tools/deployment/002-build-charts.sh
        - ./tools/deployment/003-prepare-k8s.sh
        - ./tools/deployment/004-make-images.sh
        - ./tools/deployment/005-calicoctl-utility.sh
        - ./tools/deployment/010-ceph-utility.sh
        - ./tools/deployment/020-compute-utility.sh
        - ./tools/deployment/030-etcdctl-utility.sh
        - ./tools/deployment/040-mysqlclient-utility.sh
        - ./tools/deployment/050-openstack-utility.sh
        - ./tools/deployment/060-postgresql-utility.sh

- job:
    name: airship-porthole-run-functional-tests-ubuntu_noble-kubeadm-2025-2
    parent: porthole-infra-deploy
    nodeset: treasuremap-airskiff-1node-ubuntu_jammy
    irrelevant-files: *irrelevant-files
    run:
      - tools/gate/playbooks/airship-run-scripts.yaml
      - tools/gate/playbooks/run-functional-tests.yaml
    vars:
      osh_params:
        openstack_release: "2025.2"
        container_distro_name: ubuntu
        container_distro_version: noble
        feature_gates: images
      DISTRO: ubuntu_noble

- job:
    name: airship-porthole-run-functional-tests-ubuntu_jammy-kubeadm-2025-2
    parent: porthole-infra-deploy
    nodeset: treasuremap-airskiff-1node-ubuntu_jammy
    irrelevant-files: *irrelevant-files
    run:
      - tools/gate/playbooks/airship-run-scripts.yaml
      - tools/gate/playbooks/run-functional-tests.yaml
    vars:
      osh_params:
        openstack_release: "2025.2"
        container_distro_name: ubuntu
        container_distro_version: jammy

- job:
    name: airship-porthole-run-functional-tests-ubuntu_jammy-kubeadm-2025-1
    parent: porthole-infra-deploy
    nodeset: treasuremap-airskiff-1node-ubuntu_jammy
    irrelevant-files: *irrelevant-files
    run:
      - tools/gate/playbooks/airship-run-scripts.yaml
      - tools/gate/playbooks/run-functional-tests.yaml
    vars:
      osh_params:
        openstack_release: "2025.1"
        container_distro_name: ubuntu
        container_distro_version: jammy

- job:
    name: airship-porthole-openstack-tox-py310-kubeadm
    parent: porthole-infra-deploy
    nodeset: treasuremap-airskiff-1node-ubuntu_jammy
    irrelevant-files: *irrelevant-files
    run:
      - tools/gate/playbooks/airship-run-scripts.yaml
      - tools/gate/playbooks/run-tox-tests.yaml
    vars:
      tox_envlist: py310

- job:
    name: airship-porthole-openstack-tox-cover-kubeadm
    parent: porthole-infra-deploy
    nodeset: treasuremap-airskiff-1node-ubuntu_jammy
    irrelevant-files: *irrelevant-files
    run:
      - tools/gate/playbooks/airship-run-scripts.yaml
      - tools/gate/playbooks/run-tox-tests.yaml
    vars:
      tox_envlist: cover

- secret:
    name: quay_credentials
    data:
      username: !encrypted/pkcs1-oaep
        - SQ0e+mvFN7eU+snMDhXC417r3yy+OoZ+QQcAPAoI2xuUDbZOrCSXIlRATrNZX+NrRx/sT
          GoxeeScqpX3hnBTHAvWn6iDzVoSIOgW8aG4+/kCjU1dtKzPgyuo4t+rFEe1iplLFyG1P1
          xshMrc8dRpAJTjyUwWzY1zatb46LEBK1DD15kkAaS+6KKfD2dH/AX3XYzp3671cdsXtC7
          R7Lm8lKh2MYYmF+ybuCd/JbeuH2aLQc1pLnigPBWJgslzxQ2F2hLXssj8cd+rGSxQ8jVG
          SCqFkyggBdv/TGQdhihnse8Taj8tqgmqbh5KPZIKeCM5ekXbsCMuI1KNH0Fr7UeffOYNU
          5CJsWnuZoX5xQxcRHWAprBaGr8jr6EeklW896GC7wMcFq+C4166H1Y44NMrLtzAlXEs8p
          uO6Vl2AGqt4/ORkJ7aIUdjI21u0r7ULEFcj+Q7hMoC0q81f1RVqbvTWtAi6CfjiUdpEwm
          vwpyfwUP4JugjC3UALe4tMyMO5pQiAIPzYs34/skqxvEQN+5+8BrBnr2tNAIbxMmgpZOU
          Ov89WfURzb7pxBbVgC6HuyX2mQi3OHdYS33TM9e+pXgLN8XK7dzASaCFXa0zjA1xj4pHh
          oBO66rVON6DsjEmliMUHLnkgXJnqqm9pLEa+avCuK0Kt7i5st1DBnxK/Goy2ec=
      password: !encrypted/pkcs1-oaep
        - CuInAjNp1dAXxxNzfs9O9I7+T6OJLx4gaPeafLxfjJs4uCRC8L6N1Kcyc1QPYlr6hfvFz
          D8Er9OKTzbmQixDxGzCSJh/RRcpjwh8GJMn7cvGYMTsrWcYzvK2RC5778huxVnwT0gWiB
          TaqUqOBsHQMlXumEAKO7qqaKxJ4LadXMp/eqcyVfCw1roEOO69QqhBajwhk/5RS3qm6QZ
          KGr0T3AfDAtF276e4GI9L5paVNjME7Au22+S1pVaIxX91/qx3HFAz+HSErvhxGHVKhHr4
          4G/YygeSJMWyKpk28kjoncxgzHNwREXZXbRabMwXoGuweOB4ZZ7JXy9yEkagojx0buBtn
          Phv48p/8C/7ZN3v8xOiHRAnLk6jsWA4cu5Zhplark22Uq+d7MtlEgRpWvqDBWNF+9GCOQ
          Vlpomy02Nj4PkZZDKY7Eo3uf/+3aa8/hhvJursqv6VvqwYl75euT8Immo1EUw/Hw4PBpJ
          JXcwlGoK6kvXmYaG2c7yEiH2xNtTzVTai10fsalubQWR4FTmJA5LU9+HatHBa46XLy4gS
          vMHs2uJudmxhqLIhs5Er248FVjfxw7le5dPun3ir4J7Mjgypu5y8eLCMZAFIwpeqlJrVU
          uih8ByaTlSEh6FBzle7Hb330RjSztC4pX6xiNAmtkpxhF2rEEFS66B/ixwCphQ=

- secret:
    name: quay_credentials_2026
    data:
      username: !encrypted/pkcs1-oaep
        - Y+U2SPPlorlAaXK/Tiu2NJtLiT5jznrCUB8VpeXjpdIo26JcixIaaec+806oRjcPZlA0+
          jag67Pp4cl4OQIxJjuc1autmy+I76tP0GIQBYejoXvNOBwsCHHDkEbq3EIWVxt1KTy1bN
          jX/8FT68DgwpM1iubpZl8V/3H1Y99+MN1cG9nSL35XZj682LfPZ7YX1B5otgs/OVDkrXZ
          0Aw5xMpuBAdgr2tI6wgkc5vrmgGL85H/vMY+0QyCYtpuswUCkCCd6YXoodBN+u+VeqND0
          UBKjRQN3o/15GtAnP5tNPWNwu1e01q6b/6DSFodljB2f5TDlwQmed87gk4h2SoYpg8mqR
          nz2aiqDgMTufIpG6bjJqoeBPHRimoL3aUaRJaEROfx9dnCfh1u4HeRwE2vUpZ8lz91CFA
          d9YPXpZF4t+mUAFcBhyIbiKnSKwOXlsUBlGXl8grSbFHqLJtg/R07KDcMQQONg3EbbEJt
          9OtrBrrVvloddv45Jsqtp4G2VOoxqHfHz5q+D35YVmiFsXfPwKPDbYTL3zU1X4WKHHxs4
          8j2Elno4/E0vJrlGa9PIXbM9D3/JWORwkDzSCgVW/rrRfdZjsX24/4ioiU3ZJj7UMhugd
          S3x223fZvRroadGl7CnWk3x99vb8pjeMfZ0zAL7HBAEuib5va2sdCr5UVzzsIA=
      password: !encrypted/pkcs1-oaep
        - PxT9oBl5cazLCoVlOOQWKD1Knaxj2ZNstVQZmHf656NKFE/DPKKBXZG11XXjKQue/F3Va
          H605t/z5IN4S1RSBG1QNGHXDze+1Ygp3sFoXwm6gxVfQKm+3fZW8vqW8QKVSdKCo81OJQ
          N67mciInbuwJY0JnSKlaNpTJkhSWKGil5YoBor4pSqtfMHdhVmYWgxMdsBmjVjm9lqekr
          u2Kd8qHfbGgse1sm7/SwIes1hueeqjjja8dA1AkEvVDO3y9nhxL8SwS9jl6xQWPV2e1q4
          TWJ6yN8A+QH7+3qKm9RDWBh8otustP8wo/p2ytktqSTfFJP1yJ2xJHQyFmgId0v6zdQh0
          xXPy4ink4ZtSkZOnL84wCur0OPmL8Ldh176O7nxv7zb0IwWZXuKVvL8Wek+IzKq4wo+BS
          Y5Qb7kGyx1BGhOMN75ZuJe0xeIsUbJpeheDIb5lRT4mPCedtZBGKLLuPfB6ml5IA3JKrk
          B/E9PV47z0xadLwfdGn7abmAKLp6tV+g45DzbWdgkRdxyuJe8UeJB8M9bAEfBAIPsenSf
          qT9qoqAyWSRLIXjWqJUQW+rv20g0WGD9buNn/OUeoFWSnQLwuS6zkvcDx54GM81hkARZM
          pj+iVzyKg1Fke084w3a1ckH9m6veb/B80f/pAyKmZhWddx0cK/gh3QedciY2WQ=

- job:
    name: porthole-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/porthole to airshipit/porthole
    vars:
      git_mirror_repository: airshipit/porthole
    secrets:
      - name: git_mirror_credentials
        secret: porthole-airshipit-github-ed25519-secret-2026-01-13
        pass-to-parent: true

- secret:
    name: porthole-airshipit-github-ed25519-secret-2026-01-13
    data:
      user: git
      host: github.com
      host_key: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      ssh_key: !encrypted/pkcs1-oaep
        - J09qgnA3NV9xayksrkts4LB4RkHV8INYKt/Y1BmIEz74GbC6h52yDXO441yC+YY5gmrxm
          EiWBneSqYlvNpEYwuh9GhzS4/UJ5u6cgfNSrawOZeyHOlC0IFpAsa9NkpHRU/81OBZJLh
          m84B8a5cgWsnefJp68eATKX7glUKDMOOUxgMI2u+x45qujAI987uJI4XmKiI69npYgtcj
          7uXWoreJoWDZgeIBRlIsTfb7h2ztCMZJ1yPBFXFapzUtUACunDQM2NHAt+eKSxlpt8cHy
          LYKfPpgM8ntjebEf5aWuGWBYEUeZanBailRqZ1as2aWhKjfPB02AP0aUO9cUyy95aRKTr
          R9cuCFvP5hlGBphErohOIkUKjMPNCKYzWw+t+lxbU3kh2O+o02O/dBcCXZiksvmouBLxi
          GSkoxwLj/P5mFwdUi5BZcVS8wE05djIUr1amSOFWTYwN0wHmDVh93QMRyfkVSaQklzOqo
          yW/FU0XatkOitkz04wK9EVgH5eQVpNXT7NqMmzCjG/UZuj229N+lzFfWeERtsA/58I9JH
          op9TU45Ke+Op2wi2XyTj+eSSo5MTltHQ/a3zR1xQQTB8QiUE1/kkbaGNQeYcABoPRoFSD
          GC3OjpkI0k7SN9VUZUURAEPNuft+v+BWBhYok1wi4KVtPoeBdWcV57cFTL9jTc=
...
